config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  get '/dashboard', to: "users#dashboard"
  resources :events do
    resources :tickets, only: [:create]
   end
  resources :tickets, only: [:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :tickets, dependent: :destroy
  has_many :users, through: :tickets
  has_one_attached :photo

  validates :title, :description, :datetime, :venue, :capacity, :category, :end_time, presence: true
  CATEGORIES = ["Dine out", "Cooking"]
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :status, inclusion: { in: %w[pending accepted declined] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tickets, dependent: :destroy
  has_many :events, through: :tickets
  has_one_attached :photo
  has_many :events_as_host, foreign_key: :user_id, class_name: "Event"

  validates :email, :password, :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb

    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name photo birthday description])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name photo birthday description])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @events = policy_scope(Event).order(created_at: :desc)
  end

  def show
    @ticket = Ticket.new
    authorize @event
  end

  def new
    @event = Event.new
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    authorize @event
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def edit
    authorize @event
  end

  def update
    authorize @event

    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def destroy
    authorize @event
    @event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :datetime, :venue, :capacity, :category, :user, :end_time, :photo)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def create
    @ticket = Ticket.new(ticket_params)
    @event = Event.find(params[:event_id])
    @ticket.user = current_user
    @ticket.event = @event
    authorize @ticket
    if @ticket.save
      redirect_to event_path(@event)
    else
      render "events/show"
    end
  end

  def update
    @ticket = Ticket.find(params[:id])
    authorize @ticket

    @ticket.update(ticket_params)
    redirect_back fallback_location: event_path(@ticket.event)
  end

  private

  def ticket_params
    params.require(:ticket).permit(:status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: %i[show destroy update]

  def dashboard
    @user = current_user
    @hosting = @user.events_as_host
    @accepted = @user.events.where("tickets.status = ?", "accepted")
    @pending = @user.events.where("tickets.status = ?", "pending")
    authorize @user
  end

  def show
    authorize @user
  end

  def update
    if @user.update(user_params)
      redirect_to :show
    else
      render :edit
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to :index
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to :index
  end

  def load_event_tab
    respond_to do |format|
      format.js
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :description, :birthday, :email, :password, :photo)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<%= simple_form_for (@event) do |f| %>
  <%= f.error_notification %>

 <div class="form-inputs">
    <%= f.input :title,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "title" }%>
    <%= f.input :category,
                collection: Event::CATEGORIES,
                include_blank: false,
                input_html: { autocomplete: "category" }%>
    <%= f.input :datetime,
                required: true,
                input_html: { autocomplete: "datetime" }%>
    <%= f.input :end_time,
                input_html: { autocomplete: "end_time" } %>
    <%= f.input :description,
                input_html: { autocomplete: "description" } %>
    <%= f.input :capacity,
                input_html: { autocomplete: "capacity" }%>
    <%= f.input :venue,
                input_html: { autocomplete: "venue" }%>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="mt-3">
    <%= f.submit "Create Dine", class: 'btn btn-primary button-green' %>
    <%= link_to 'Cancel', '/home', class: 'btn btn-secondary ml-2' %>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="container-fluid">
  <div class="container-cards-events">
    <% @events.each do |event| %>
    <%= link_to(event) do %>
      <% d = event.datetime %>
      <div class="card-event mb-3">
      <% background_url = event.photo.attached? ? cl_image_path(event.photo.key, height: 300, width: 300, crop: :fill)  : "https://images.unsplash.com/photo-1543007630-9710e4a00a20?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=975&q=80" %>

        <div class="card-event-picture"
        style="background-image: linear-gradient(rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, .5) 30%, rgba(0, 0, 0, 0.8) 100%), url( <%= background_url %>);">

          <h1 class="event-title"><%= event.title %></h1>
          <p class="event-venue"><%= event.venue %></p>
        </div>
        <div class="card-event-info">
          <div class="card-event-info-left align-items-center mb-2">
            <div class="card-event-date d-flex align-items-center">
              <h1 class="align-text-bottom mb-0 mr-2"><%= d.strftime("#{d.day.ordinalize}")%></h1>
              <div class="card-event-date-stacked">
                <small><h6 class="mb-1"><%= d.strftime('%b') %></h6></small>
                <h5>(<%= d.strftime('%a') %>)</h5>
              </div>
            </div>
            <h5 class="ml-2"><%= d.strftime("%l:%M%P") %> - 9pm</h5>
          </div>
          <div class="card-event-info-right">
          <% if event.user.photo.attached? %>
            <%= cl_image_tag(event.user.photo.key, class: "card-event-avatar") %>
              <% else %>
              <%= image_tag("https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80", class: "card-event-avatar") %>
            <% end %>
            <p class="mb-2"><strong><%= event.user.first_name %></strong></p>
            <p class="mb-0">2/<%= event.capacity %></p>
            <p class="mb-0">capacity</p>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="event-form">
        <h1 class="title-green">Create a new dine event</h1>
        <div class="mt-3">
          <%= render "form", event: @event %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container flex ">
  <div> <%= render 'shared/event_details', event: @event%></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friendsofl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="main-container " style="min-height: calc(100vh - 140px - 56px); padding-top: 24px; padding-bottom: 24px;">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<header class="header">
  <!-- Header Content -->
  <div class="header_content">
    <h1 class="site-name">More delicious together.</h1>
    <%= link_to "Find like-minded dine buddy", events_path, class: "btn btn-outline-primary button-green" %>
  <!-- end Header Content -->
  </div>

  <div class="home-content">
  </div>
</header>

app/views/shared/_approval.html.erb
<div class="container-window d-flex flex-column align-items-stretch">

  <% accepted = event.tickets.where(status: "accepted") %>
  <h2>Attendees (<%= accepted.length + 1 %>)</h2>
  <ul style="list-style-type:none">

    <li class="d-flex attendee align-items-center">
        <%= render "shared/avatar", user: event.user %>
        <p class="mb-0 text-decoration-none"><%= link_to event.user.first_name.capitalize, user_path(event.user) %> (Host)</p>
    </li>

    <% if event.user != current_user %>

      <% accepted.each do |ticket| %>
        <li>
          <div class="d-flex attendee align-items-center text-decoration-none">
            <%= render "shared/avatar", user: ticket.user %>
            <%= link_to ticket.user.first_name, user_path(ticket.user) %>
          </div>
        </li>
      <% end %>

    <% else %>

      <% event.tickets.where(status: "pending").each do |ticket| %>
        <li>
          <div class="d-flex attendee align-items-center justify-content-between">
            <%= render "shared/avatar", user: ticket.user %>
            <%= link_to ticket.user.first_name, user_path(ticket.user) %>

            <div class="d-flex align-items-center">
              <%= simple_form_for(ticket) do |f| %>
                <%= f.input :status, input_html: { value: "accepted" }, as: :hidden %>
                <%= button_tag type: 'submit', class: "my-button btn-accept" do %>
                  <i class="far fa-check-circle"></i>
                <% end %>
              <% end %>
              <%= simple_form_for(ticket) do |f| %>
                <%= f.input :status, input_html: { value: "declined" }, as: :hidden %>
                <%= button_tag type: 'submit', class: "my-button btn-decline" do %>
                  <i class="far fa-times-circle"></i>
                <% end %>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>

      <% accepted.each do |ticket| %>
        <li>
          <div class="d-flex attendee align-items-center justify-content-between">
            <%= render "shared/avatar", user: ticket.user %>
            <%= link_to ticket.user.first_name, user_path(ticket.user) %><h5 class="font-italic pr-2">Accepted</h5>
          </div>
        </li>
      <% end %>

    <% end %>
  </ul>
</div>

app/views/shared/_avatar.html.erb
<% if user.photo.attached? %>
  <%= link_to cl_image_tag(user.photo.key, class: "avatar rounded-circle mr-3"), user_path(user) %>
<% else %>
  <%= image_tag("https://icon-library.com/images/no-profile-pic-icon/no-profile-pic-icon-27.jpg", class: "avatar rounded-circle mr-3") %>
<% end %>

app/views/shared/_event_details.html.erb
<div class="event-container flex">
  <div>
    <% category_icon = event.category == 'Cooking' ? 'chef@4x.png' : 'cutlery@4x.png' %>
    <h5 class="mb-3"> <%= image_tag category_icon, height:30 %>  <%= event.category %></h5>
    <div class="event-title-show mb-4">
      <h1 class="text-orange"><%= event.title %></h1>
    </div>


    <div class="flex">
      <div class="flex align-items-center host-info my-3" >
        <% if event.user.photo.attached? %>
          <%= link_to cl_image_tag(event.user.photo.key, class: "avatar-large mr-3"), user_path(event.user) %>
        <% else %>
          <%= image_tag("https://images.unsplash.com/photo-1543007630-9710e4a00a20?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=975&q=80", class: "avatar-large") %>
        <% end %>
        <p class="mb-0 text-decoration-none"> Hosted by <%= link_to event.user.first_name.capitalize, user_path(event.user) %></p>
      </div>
      <div>
        <% if event.user != current_user %>
            <div>
              <% if Ticket.where(user: current_user, event: event).exists? %>
                <button class="btn  btn-outline-secondary button-request-grey" disabled>Request Sent</button>
              <% else %>
                <%= simple_form_for [event, Ticket.new] do |f| %>
                  <%= f.input :status, as: :hidden %>
                  <%= f.submit "Request to join", class: "btn btn-outline-primary button-green button-request-green"%>
                <% end %>
              <% end %>
            </div>
          <% end %>
      </div>
    </div>


    <div class="flex" >
      <div>
        <% if event.photo.attached? %>
          <%= cl_image_tag event.photo.key, height: 400, width: 700, crop: :fill %>
        <% else %>
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg" alt="Breakfast Pic" width=700px>
        <% end %>
        <h5 class="mt-5"> Event Details:<h5></h5>
        <%= simple_format(event.description) %>
      </div>
      <div class="card-sticky ml-3">
        <div class="p-3 mb-3 card-event-info-show">
          <% d = event.datetime %>
          <p> <%= image_tag "time-alarm@4x.png", height:30 %> <%= d.strftime("%a, %b %d %l:%M %p") %></p>
          <p><%= image_tag "pin-star@4x.png",   height:30 %> <%= event.venue %></p>
          <% if Ticket.where(user: current_user, event: event, status: "accepted").exists? %>
            <p> <%= image_tag "pin-star@4x.png",   height:30 %> <%= event.user.email %></p>
          <% end %>
        </div>

        <div class="mb-3"><%= render 'shared/approval', event: event %></div>


      </div>
    </div>
  </div>

</div>

<div class="suggestions">
  <h2>More Suggestions For You</h2>
  <div class="suggestions-cards">
    <% events = Event.all.sample(3) %>
    <% events.each do |event| %>
      <%= link_to(event) do %>
        <% d = event.datetime %>
        <div class="card-event mb-3">
        <% background_url = event.photo.attached? ? cl_image_path(event.photo.key, height: 300, width: 300, crop: :fill)  : "https://images.unsplash.com/photo-1543007630-9710e4a00a20?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=975&q=80" %>

          <div class="card-event-picture"
          style="background-image: linear-gradient(rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, .5) 30%, rgba(0, 0, 0, 0.8) 100%), url( <%= background_url %>);">

            <h1 class="event-title"><%= event.title %></h1>
            <p class="event-venue"><%= event.venue %></p>
          </div>
          <div class="card-event-info m-0">
            <div class="card-event-info-left align-items-center mb-2">
              <div class="card-event-date d-flex align-items-center">
                <h1 class="align-text-bottom mb-0 mr-2"><%= d.strftime("#{d.day.ordinalize}")%></h1>
                <div class="card-event-date-stacked">
                  <small><h6 class="mb-1"><%= d.strftime('%b') %></h6></small>
                  <h5>(<%= d.strftime('%a') %>)</h5>
                </div>
              </div>
              <h5 class="ml-2"><%= d.strftime("%l:%M%P") %> - 9pm</h5>
            </div>
            <div class="card-event-info-right">
            <% if event.user.photo.attached? %>
              <%= cl_image_tag(event.user.photo.key, class: "card-event-avatar") %>
                <% else %>
                <%= image_tag("https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80", class: "card-event-avatar") %>
              <% end %>
              <p class="mb-2"><strong><%= event.user.first_name %></strong></p>
              <p class="mb-0 mt-4"><%= event.tickets.where(status: "accepted").length + 1 %> <%= image_tag "single-02@4x.png", class: "attendee-icon" %></p>
            </div>
          </div>
        </div>
        
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="py-3 border-top my-footer">
  <div class="row h-40">
  <div class="col-4 my-auto text-center justify-items-middle"></div>
  <div class="col-4 my-auto text-center justify-content-center">
    <a href="https://www.facebook.com/sectionl.tokyo" class="fab fa-facebook-square sns" target="_blank"></a>
    <a href="https://www.instagram.com/staysection_l/" class="fab fa-instagram sns" target="_blank"></a>
    <a href="#" class="fab fa-twitter sns" target="_blank"></a>
    <p>Created by Aki, Shinya and Hayato.</p>
    <p>2020</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://images.squarespace-cdn.com/content/5eec60c93b09b86005154cce/1594183751882-RO2PIKVT9OLMSBN2WA0H/%E3%82%A2%E3%82%BB%E3%83%83%E3%83%88+2.png?content-type=image%2Fpng" %>
  <% end %>
<div>
    <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse topnav-right" id="navbarSupportedContent">

        <li class="nav-item">
          <%= link_to "My Dines", "/dashboard", class: "nav-link #{"active" if params[:controller] == "users" && params[:action] == "dashboard"}" %>
        </li>
        <li class="nav-item">
          <%= link_to "All Dines", "/events", class: "nav-link #{"active" if params[:controller] == "events" && params[:action] == "index"}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create Dines", "/events/new", class: "nav-link #{"active" if params[:controller] == "events" && params[:action] == "new"}" %>
        </li>


        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My events", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse topnav-right" id="navbarSupportedContent">


        <li class="nav-item">
          <%= link_to "All Dines", "/events", class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>

      <% end %>
    </ul>

</div>
  </div>
</div>

app/views/users/_events.html.erb
<% if events.length.zero? %>
  <div class="no-events-display">
    <h3>No events to display!</h3>
    <p>Browse the "All Events" tab to see events others have created,</p>
    <p>or click "make an event" to organize your own!</p>
  </div>
<% else %>

  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <% events.each do |event| %>
      <li class="nav-item">
        <a class="nav-link <%= 'active' if events.first == event %>" id="event-<%=event.id%>-tab" data-toggle="tab" href="#event-<%=event.id%>" role="tab" aria-controls="event-<%=event.id%>" aria-selected="false">
          <h6 class="ellipsis"><%=event.title%></h6>
        </a>
      </li>
    <% end %>
  </ul>

  <div class="tab-content" id="myTabContent">
    <% events.each do |event| %>
      <div class="tab-pane fade py-3 <%= 'show active' if events.first == event %>" id="event-<%=event.id%>" role="tabpanel" aria-labelledby="event-<%=event.id%>-tab">
        <%= render "shared/event_details", event: event %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/dashboard.html.erb
<div class="d-flex">
  <div class="side-bar">
    <%= link_to dashboard_path(tab: 'hosting'), class: "side-link #{'active' if params[:tab] == "hosting"}" do %>
      <%= image_tag "event-confirm@4x.png", class: "side-link-icon" %>
      <p class="mb-0 text-decoration-none">hosting</p>
    <% end %>
    <%= link_to dashboard_path(tab: 'accepted'), class: "side-link #{'active' if params[:tab] == 'accepted'}" do %>
      <%= image_tag "ticket@4x.png", class: "side-link-icon" %>
      <p class="mb-0 text-decoration-none">accepted</p>
    <% end %>
    <%= link_to dashboard_path(tab: 'pending'), class: "side-link #{'active' if params[:tab].nil? || params[:tab] == 'pending'}" do %>
      <%= image_tag "hourglass@4x.png", class: "side-link-icon" %>
      <p class="mb-0 text-decoration-none">pending</p>
    <% end %>
  </div>

  <div class="container container-events-tab">
    <% if params[:tab] == "hosting" %>
      <h1 class="title-green">Hosting</h1>
      <%= render "users/events", events: @hosting %>
    <% elsif params[:tab] == "accepted" %>
      <h1 class="title-green">Attending</h1>
      <%= render "users/events", events: @accepted %>
    <% elsif params[:tab] == "pending" || params[:tab].nil? %>
      <h1 class="title-green">Pending requests</h1>
      <%= render "users/events", events: @pending %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
    <h1 class="profile-top"> Hi! I'm <%= @user.first_name %> </h1>
    <div class="profile">
    <% if @user.photo.attached? %>
      <%= cl_image_tag @user.photo.key, class: "avatar-extra-large" %>
    <% else %>
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg" alt="" width=700px>
    <% end %>

    <% user_age = ((DateTime.now - @user.birthday.to_date)/365).floor %>
    <p class="mt-4"> Age: <%= user_age %></p>
    <%= simple_format(@user.description) %>
  </div>